version: '3'

services:

  MySQLdb:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: devadmin
      MYSQL_PASSWORD: devpass
      MYSQL_ROOT_PASSWORD: rootpass

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  onlinelib:
    build: back/
    ports:
    - "4000:80"
    environment:
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_ENVIRONMENT: Development
