// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251217180704_Initial_WorkEdition_Admin")]
    partial class Initial_WorkEdition_Admin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Data.Entities.AdminAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_type");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.HasKey("Id")
                        .HasName("pk_admin_audit_logs");

                    b.HasIndex("ActionType")
                        .HasDatabaseName("ix_admin_audit_logs_action_type");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_admin_audit_logs_admin_user_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_admin_audit_logs_created_at");

                    b.ToTable("admin_audit_logs", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.AdminRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_admin_refresh_tokens");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_admin_refresh_tokens_admin_user_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_admin_refresh_tokens_expires_at");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_refresh_tokens_token");

                    b.ToTable("admin_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_email");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.BookFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<int>("Format")
                        .HasColumnType("integer")
                        .HasColumnName("format");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<string>("Sha256")
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_book_files");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("ix_book_files_edition_id");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_book_files_sha256");

                    b.ToTable("book_files", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.Bookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<string>("Locator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locator");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_bookmarks");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("ix_bookmarks_chapter_id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("ix_bookmarks_edition_id");

                    b.HasIndex("UserId", "EditionId")
                        .HasDatabaseName("ix_bookmarks_user_id_edition_id");

                    b.ToTable("bookmarks", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("chapter_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<string>("Html")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html");

                    b.Property<string>("PlainText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plain_text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "PlainText" });

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("WordCount")
                        .HasColumnType("integer")
                        .HasColumnName("word_count");

                    b.HasKey("Id")
                        .HasName("pk_chapters");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_chapters_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("EditionId", "ChapterNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_chapters_edition_id_chapter_number");

                    b.HasIndex("EditionId", "Slug")
                        .HasDatabaseName("ix_chapters_edition_id_slug");

                    b.ToTable("chapters", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.Edition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorsJson")
                        .HasColumnType("text")
                        .HasColumnName("authors_json");

                    b.Property<string>("CoverPath")
                        .HasColumnType("text")
                        .HasColumnName("cover_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublicDomain")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public_domain");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<Guid?>("SourceEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_edition_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_editions");

                    b.HasIndex("Slug")
                        .HasDatabaseName("ix_editions_slug");

                    b.HasIndex("SourceEditionId")
                        .HasDatabaseName("ix_editions_source_edition_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_editions_status");

                    b.HasIndex("WorkId", "Language")
                        .IsUnique()
                        .HasDatabaseName("ix_editions_work_id_language");

                    b.ToTable("editions", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.IngestionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("BookFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_file_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid?>("SourceEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_edition_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("target_language");

                    b.Property<Guid?>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_jobs");

                    b.HasIndex("BookFileId")
                        .HasDatabaseName("ix_ingestion_jobs_book_file_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_ingestion_jobs_created_at");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("ix_ingestion_jobs_edition_id");

                    b.HasIndex("SourceEditionId")
                        .HasDatabaseName("ix_ingestion_jobs_source_edition_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ingestion_jobs_status");

                    b.HasIndex("WorkId")
                        .HasDatabaseName("ix_ingestion_jobs_work_id");

                    b.ToTable("ingestion_jobs", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<string>("Locator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locator");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_notes");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("ix_notes_chapter_id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("ix_notes_edition_id");

                    b.HasIndex("UserId", "EditionId")
                        .HasDatabaseName("ix_notes_user_id_edition_id");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.ReadingProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_id");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<string>("Locator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locator");

                    b.Property<double?>("Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("percent");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reading_progresses");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("ix_reading_progresses_chapter_id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("ix_reading_progresses_edition_id");

                    b.HasIndex("UserId", "EditionId")
                        .IsUnique()
                        .HasDatabaseName("ix_reading_progresses_user_id_edition_id");

                    b.ToTable("reading_progresses", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_external_id")
                        .HasFilter("external_id IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.Work", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_works");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_works_slug");

                    b.ToTable("works", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.AdminAuditLog", b =>
                {
                    b.HasOne("Infrastructure.Data.Entities.AdminUser", "AdminUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_audit_logs_admin_users_admin_user_id");

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.AdminRefreshToken", b =>
                {
                    b.HasOne("Infrastructure.Data.Entities.AdminUser", "AdminUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_refresh_tokens_admin_users_admin_user_id");

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.BookFile", b =>
                {
                    b.HasOne("Infrastructure.Data.Entities.Edition", "Edition")
                        .WithMany("BookFiles")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_files_editions_edition_id");

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.Bookmark", b =>
                {
                    b.HasOne("Infrastructure.Data.Entities.Chapter", "Chapter")
                        .WithMany("Bookmarks")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookmarks_chapters_chapter_id");

                    b.HasOne("Infrastructure.Data.Entities.Edition", "Edition")
                        .WithMany()
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookmarks_editions_edition_id");

                    b.HasOne("Infrastructure.Data.Entities.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookmarks_users_user_id");

                    b.Navigation("Chapter");

                    b.Navigation("Edition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.Chapter", b =>
                {
                    b.HasOne("Infrastructure.Data.Entities.Edition", "Edition")
                        .WithMany("Chapters")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chapters_editions_edition_id");

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.Edition", b =>
                {
                    b.HasOne("Infrastructure.Data.Entities.Edition", "SourceEdition")
                        .WithMany("TranslatedEditions")
                        .HasForeignKey("SourceEditionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_editions_editions_source_edition_id");

                    b.HasOne("Infrastructure.Data.Entities.Work", "Work")
                        .WithMany("Editions")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_editions_works_work_id");

                    b.Navigation("SourceEdition");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.IngestionJob", b =>
                {
                    b.HasOne("Infrastructure.Data.Entities.BookFile", "BookFile")
                        .WithMany("IngestionJobs")
                        .HasForeignKey("BookFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_jobs_book_files_book_file_id");

                    b.HasOne("Infrastructure.Data.Entities.Edition", "Edition")
                        .WithMany("IngestionJobs")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_jobs_editions_edition_id");

                    b.HasOne("Infrastructure.Data.Entities.Edition", "SourceEdition")
                        .WithMany()
                        .HasForeignKey("SourceEditionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ingestion_jobs_editions_source_edition_id");

                    b.HasOne("Infrastructure.Data.Entities.Work", "Work")
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ingestion_jobs_works_work_id");

                    b.Navigation("BookFile");

                    b.Navigation("Edition");

                    b.Navigation("SourceEdition");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.Note", b =>
                {
                    b.HasOne("Infrastructure.Data.Entities.Chapter", "Chapter")
                        .WithMany("Notes")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notes_chapters_chapter_id");

                    b.HasOne("Infrastructure.Data.Entities.Edition", "Edition")
                        .WithMany()
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notes_editions_edition_id");

                    b.HasOne("Infrastructure.Data.Entities.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notes_users_user_id");

                    b.Navigation("Chapter");

                    b.Navigation("Edition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.ReadingProgress", b =>
                {
                    b.HasOne("Infrastructure.Data.Entities.Chapter", "Chapter")
                        .WithMany("ReadingProgresses")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_progresses_chapters_chapter_id");

                    b.HasOne("Infrastructure.Data.Entities.Edition", "Edition")
                        .WithMany()
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_progresses_editions_edition_id");

                    b.HasOne("Infrastructure.Data.Entities.User", "User")
                        .WithMany("ReadingProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_progresses_users_user_id");

                    b.Navigation("Chapter");

                    b.Navigation("Edition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.AdminUser", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.BookFile", b =>
                {
                    b.Navigation("IngestionJobs");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.Chapter", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Notes");

                    b.Navigation("ReadingProgresses");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.Edition", b =>
                {
                    b.Navigation("BookFiles");

                    b.Navigation("Chapters");

                    b.Navigation("IngestionJobs");

                    b.Navigation("TranslatedEditions");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.User", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Notes");

                    b.Navigation("ReadingProgresses");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.Work", b =>
                {
                    b.Navigation("Editions");
                });
#pragma warning restore 612, 618
        }
    }
}
