namespace Domain.Enums;

/// <summary>
/// Provenance of SEO content on an entity. Drives auto-skip logic during bulk backfill —
/// entities marked <c>Manual</c> are skipped unless admin explicitly overrides.
/// </summary>
public enum SeoSource
{
    /// <summary>Admin-written or legacy pre-automation content. Skipped by auto jobs.</summary>
    Manual = 0,

    /// <summary>All SEO fields generated by a <c>SeoBackfillJob</c>.</summary>
    Auto = 1,

    /// <summary>Mix of manual and auto-generated fields.</summary>
    Hybrid = 2
}
