#!/bin/bash
# Polls DB for Running codegen jobs and executes them on the host.
# Requires: claude CLI (Max subscription), gh CLI, psql.
# Usage: ./infra/scripts/codegen-poll.sh
# Run via: cron, systemd, or just in a tmux/screen session.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
POLL_INTERVAL=10

# Status codes (match CodeGenJobStatus enum)
STATUS_RUNNING=1
STATUS_COMPLETED=2
STATUS_FAILED=3

# Load .env for DB connection
if [ -f "$REPO_DIR/.env" ]; then
  set -a
  source "$REPO_DIR/.env"
  set +a
fi

DB_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}"

log() { echo "[$(date '+%H:%M:%S')] $*"; }

get_next_job() {
  psql "$DB_URL" -tAc "
    SELECT id FROM code_gen_jobs
    WHERE status = 1
    ORDER BY started_at
    LIMIT 1;" 2>/dev/null | tr -d '[:space:]'
}

get_job_field() {
  local job_id="$1" field="$2"
  psql "$DB_URL" -tAc "
    SELECT $field FROM code_gen_jobs WHERE id = '$job_id';" 2>/dev/null | head -1
}

update_job() {
  local job_id="$1"
  shift
  psql "$DB_URL" -c "UPDATE code_gen_jobs SET $* WHERE id = '$job_id';" 2>/dev/null
}

process_job() {
  local job_id="$1"

  # Validate UUID format
  [[ "$job_id" =~ ^[0-9a-f-]{36}$ ]] || { log "Invalid job ID: $job_id"; return 1; }

  local description
  local max_iterations
  description=$(get_job_field "$job_id" "description")
  max_iterations=$(get_job_field "$job_id" "max_iterations")
  local branch="codegen/${job_id//-/}"
  local progress_file="/tmp/codegen-progress-${job_id}.txt"

  log "Processing job $job_id: $description (max $max_iterations iterations)"

  cd "$REPO_DIR"

  # Create branch
  git checkout -b "$branch" main 2>/dev/null || git checkout "$branch"
  update_job "$job_id" "branch_name = '$branch'"

  # Progress file
  echo "" > "$progress_file"

  # Run iterations
  for i in $(seq 1 "$max_iterations"); do
    # Check if cancelled
    local status
    status=$(get_job_field "$job_id" "status")
    if [ "$status" != "$STATUS_RUNNING" ]; then
      log "Job $job_id cancelled"
      break
    fi

    log "Iteration $i/$max_iterations"

    local output
    output=$(bash "$REPO_DIR/infra/scripts/codegen-once.sh" "$description" "$progress_file" 2>&1) || true

    # Update progress
    local truncated
    truncated=$(echo "$output" | tail -c 10000 | sed "s/'/''/g")
    update_job "$job_id" "completed_iterations = $i, log_output = '$truncated'"

    # Check completion
    if echo "$output" | grep -q "CODEGEN_COMPLETE"; then
      log "Task complete after $i iterations"
      break
    fi
  done

  # Check if cancelled during execution
  local final_status
  final_status=$(get_job_field "$job_id" "status")
  if [ "$final_status" != "$STATUS_RUNNING" ]; then
    log "Job was cancelled, skipping PR"
    git checkout main 2>/dev/null || true
    rm -f "$progress_file"
    return
  fi

  # Push and create PR
  if ! git push -u origin "$branch" 2>&1; then
    log "Failed to push branch $branch"
    update_job "$job_id" "status = $STATUS_FAILED, error = 'git push failed', finished_at = NOW()"
    git checkout main 2>/dev/null || true
    rm -f "$progress_file"
    return
  fi

  local pr_title="${description:0:70}"
  local pr_url
  pr_url=$(gh pr create \
    --title "$pr_title" \
    --body "$(cat <<EOF
## Auto-generated by CodeGen

$description

🤖 Generated with Claude Code
EOF
)" \
    --head "$branch" 2>&1) || {
    log "Failed to create PR, but code is pushed to $branch"
    update_job "$job_id" "status = $STATUS_COMPLETED, error = 'PR creation failed, branch pushed', finished_at = NOW()"
    git checkout main 2>/dev/null || true
    rm -f "$progress_file"
    return
  }

  # Mark completed
  local escaped_url
  escaped_url=$(echo "$pr_url" | sed "s/'/''/g")
  update_job "$job_id" "status = $STATUS_COMPLETED, pr_url = '$escaped_url', finished_at = NOW()"
  log "Job $job_id completed. PR: $pr_url"

  # Cleanup
  git checkout main 2>/dev/null || true
  rm -f "$progress_file"
}

# Main loop
log "CodeGen host poller started (repo: $REPO_DIR)"
while true; do
  job_id=$(get_next_job)
  if [ -n "$job_id" ]; then
    process_job "$job_id" || {
      log "Job $job_id failed"
      update_job "$job_id" "status = $STATUS_FAILED, error = 'Script failed', finished_at = NOW()"
      git checkout main 2>/dev/null || true
    }
  fi
  sleep "$POLL_INTERVAL"
done
