#!/bin/bash
# Polls DB for Running codegen jobs and executes them on the host.
# Requires: claude CLI (Max subscription), gh CLI, docker (for psql via db container).
# Usage: ./infra/scripts/codegen-poll.sh
# Run via: cron, systemd, or just in a tmux/screen session.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
POLL_INTERVAL=10

# Status codes (match CodeGenJobStatus enum)
STATUS_RUNNING=1
STATUS_COMPLETED=2
STATUS_FAILED=3

# Load .env for DB connection
if [ -f "$REPO_DIR/.env" ]; then
  set -a
  source "$REPO_DIR/.env"
  set +a
fi

# Validate required env vars
for var in POSTGRES_USER POSTGRES_DB; do
  if [ -z "${!var:-}" ]; then
    echo "ERROR: $var not set. Check .env file." >&2
    exit 1
  fi
done

# Add claude CLI to PATH (VS Code extension binary)
for claude_dir in "$HOME"/.vscode/extensions/anthropic.claude-code-*/resources/native-binary; do
  [ -d "$claude_dir" ] && export PATH="$claude_dir:$PATH" && break
done

log() { echo "[$(date '+%H:%M:%S')] $*"; }

# Use docker psql (no need to install postgresql-client on host)
db_query() {
  docker compose -f "$REPO_DIR/docker-compose.yml" exec -T db \
    psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -tAc "$1" 2>/dev/null
}

db_exec() {
  docker compose -f "$REPO_DIR/docker-compose.yml" exec -T db \
    psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "$1" 2>/dev/null
}

get_next_job() {
  db_query "SELECT id FROM code_gen_jobs WHERE status = 1 ORDER BY started_at LIMIT 1;" | tr -d '[:space:]'
}

get_job_field() {
  local job_id="$1" field="$2"
  db_query "SELECT $field FROM code_gen_jobs WHERE id = '$job_id';" | head -1
}

update_job() {
  local job_id="$1"
  shift
  db_exec "UPDATE code_gen_jobs SET $* WHERE id = '$job_id';"
}

process_job() {
  local job_id="$1"

  # Validate UUID format
  [[ "$job_id" =~ ^[0-9a-f-]{36}$ ]] || { log "Invalid job ID: $job_id"; return 1; }

  local description
  local max_iterations
  description=$(get_job_field "$job_id" "description")
  max_iterations=$(get_job_field "$job_id" "max_iterations")
  local branch="codegen/${job_id//-/}"
  local progress_file="/tmp/codegen-progress-${job_id}.txt"

  log "Processing job $job_id: $description (max $max_iterations iterations)"

  cd "$REPO_DIR"

  # Ensure clean state before branch switch
  git stash --include-untracked -q 2>/dev/null || true
  git checkout main -q 2>/dev/null || true
  git pull origin main -q 2>/dev/null || true

  # Create or reset codegen branch (force-reset handles rerun with stale commits)
  if git show-ref --verify --quiet "refs/heads/$branch" 2>/dev/null; then
    git checkout "$branch" 2>/dev/null
    git reset --hard main
  else
    git checkout -b "$branch" main 2>/dev/null
  fi

  # Verify we're on the right branch
  local current_branch
  current_branch=$(git branch --show-current)
  if [ "$current_branch" != "$branch" ]; then
    log "ERROR: Failed to checkout $branch (on $current_branch)"
    update_job "$job_id" "status = $STATUS_FAILED, error = 'git checkout failed', finished_at = NOW()"
    return 1
  fi
  update_job "$job_id" "branch_name = '$branch'"

  # Clean stale PDD from previous run (rerun scenario)
  local short_id="${job_id:0:8}"
  local pdd_file="docs/05-features/codegen-${short_id}.md"
  if [ -f "$pdd_file" ]; then
    rm "$pdd_file"
    git add "$pdd_file"
    git commit -m "reset: clean PDD for rerun" 2>/dev/null || true
  fi

  # Progress file
  echo "" > "$progress_file"

  # Run iterations
  for i in $(seq 1 "$max_iterations"); do
    # Check if cancelled
    local status
    status=$(get_job_field "$job_id" "status")
    if [ "$status" != "$STATUS_RUNNING" ]; then
      log "Job $job_id cancelled"
      break
    fi

    log "Iteration $i/$max_iterations"

    local output
    output=$(bash "$REPO_DIR/infra/scripts/codegen-once.sh" "$description" "$progress_file" "$short_id" 2>&1) || true

    # Update progress
    local truncated
    truncated=$(echo "$output" | tail -c 10000 | sed "s/'/''/g")
    update_job "$job_id" "completed_iterations = $i, log_output = '$truncated'"

    # Check completion
    if echo "$output" | grep -q "CODEGEN_COMPLETE"; then
      log "Task complete after $i iterations"
      break
    fi
  done

  # Check if cancelled during execution
  local final_status
  final_status=$(get_job_field "$job_id" "status")
  if [ "$final_status" != "$STATUS_RUNNING" ]; then
    log "Job was cancelled, skipping PR"
    git checkout main 2>/dev/null || true
    rm -f "$progress_file"
    return
  fi

  # Push and create PR
  if ! git push -u origin "$branch" --force 2>&1; then
    log "Failed to push branch $branch"
    update_job "$job_id" "status = $STATUS_FAILED, error = 'git push failed', finished_at = NOW()"
    git checkout main 2>/dev/null || true
    rm -f "$progress_file"
    return
  fi

  local pr_title="${description:0:70}"
  local pr_url
  local pr_stderr
  pr_stderr=$(mktemp)
  pr_url=$(gh pr create \
    --title "$pr_title" \
    --body "$(cat <<EOF
## Auto-generated by CodeGen

$description

🤖 Generated with Claude Code
EOF
)" \
    --head "$branch" 2>"$pr_stderr") || {
    log "Failed to create PR, but code is pushed to $branch"
    log "gh stderr: $(cat "$pr_stderr")"
    rm -f "$pr_stderr"
    update_job "$job_id" "status = $STATUS_COMPLETED, error = 'PR creation failed, branch pushed', finished_at = NOW()"
    git checkout main 2>/dev/null || true
    rm -f "$progress_file"
    return
  }
  rm -f "$pr_stderr"

  # Mark completed
  local escaped_url
  escaped_url=$(echo "$pr_url" | sed "s/'/''/g")
  update_job "$job_id" "status = $STATUS_COMPLETED, pr_url = '$escaped_url', finished_at = NOW()"
  log "Job $job_id completed. PR: $pr_url"

  # Cleanup
  git checkout main 2>/dev/null || true
  rm -f "$progress_file"
}

# Main loop
log "CodeGen host poller started (repo: $REPO_DIR)"
while true; do
  job_id=$(get_next_job)
  if [ -n "$job_id" ]; then
    process_job "$job_id" || {
      log "Job $job_id failed"
      update_job "$job_id" "status = $STATUS_FAILED, error = 'Script failed', finished_at = NOW()"
      git checkout main 2>/dev/null || true
    }
  fi
  sleep "$POLL_INTERVAL"
done
